#!/bin/bash

valid=true

while $valid; do
read -p "What is your favorite house pet: Cat or Dog?        " response

lowerResponse="${response,,}"
if [[ $lowerResponse == "cat" ]]; then
echo "meow"
valid=false
fi

if [[ $lowerResponse == "dog" ]]; then
echo "woof"
valid=false
fi
done
